---
name: CI
on:
  push:
    branches: [NOJIRA-qbee-docker-os]
    tags:
      - '*'
  pull_request:
    branches: [NOJIRA-qbee-docker-os]

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]
    timeout-minutes: 600
    container:
      image: dynamicdevices/yocto-ci-build:latest
      options: --privileged --platform linux/amd64  -v /dev/net/tun:/dev/net/tun -v /dev/kvm:/dev/kvm
    strategy:
      matrix:
        branch: [scarthgap]
        machine: [beaglebone-yocto]
        #machine: [raspberrypi3-64,raspberrypi4-64,raspberrypi5,raspberrypi0-2w-64,beaglebone-yocto]
        poky_version: ["scarthgap-5.0.6", "scarthgap-5.0.7"]
    env:
      name: build-and-test
      MACHINE: ${{ matrix.machine }}
      BRANCH: ${{ matrix.branch }}
      POKY_VERSION: ${{ matrix.poky_version }}
    steps:
      - uses: actions/checkout@v4
        with:
          clean: false
          fetch-depth: 0

      - name: Update repo poky
        run: |
          if [ ! -d ${BRANCH}/poky-${POKY_VERSION} ]; then
            git clone git://git.yoctoproject.org/poky -b ${POKY_VERSION} ${BRANCH}/poky-${POKY_VERSION}
          fi
      - name: Update repo meta-openembedded
        run: |
          if [ ! -d ${BRANCH}/meta-openembedded ]; then
            git clone https://github.com/openembedded/meta-openembedded.git -b ${BRANCH} ${BRANCH}/meta-openembedded
          else
            cd ${BRANCH}/meta-openembedded
            git pull origin ${BRANCH}
            cd ../..
          fi
          
      - name: Update repo meta-rauc
        run: |
          if [ ! -d ${BRANCH}/meta-rauc ]; then
            git clone https://github.com/rauc/meta-rauc.git -b ${BRANCH} ${BRANCH}/meta-rauc
          else
            cd ${BRANCH}/meta-rauc
            git pull origin ${BRANCH}
            cd ../..
          fi
      - name: Update repo meta-rauc-community
        run: |
          if [ ! -d ${BRANCH}/meta-rauc-community ]; then
            git clone https://github.com/rauc/meta-rauc-community.git -b ${BRANCH} ${BRANCH}/meta-rauc-community
          else
            cd ${BRANCH}/meta-rauc-community
            git pull origin ${BRANCH}
            cd ../..
          fi
  
      - name: Update repo meta-raspberrypi
        run: |
          if [ ! -d ${BRANCH}/meta-raspberrypi ]; then
            git clone https://git.yoctoproject.org/meta-raspberrypi.git -b ${BRANCH} ${BRANCH}/meta-raspberrypi
          else
            cd ${BRANCH}/meta-raspberrypi
            git pull origin ${BRANCH}
            cd ../..
          fi
      - name: Update repo meta-security
        run: |
          if [ ! -d ${BRANCH}/meta-security ]; then
            git clone https://git.yoctoproject.org/meta-security.git -b ${BRANCH} ${BRANCH}/meta-security
          else
            cd ${BRANCH}/meta-security
            git pull origin ${BRANCH}
            cd ../..
          fi
      - name: Update repo meta-virtualization
        run: |
          if [ ! -d ${BRANCH}/meta-virtualization ]; then
            git clone https://git.yoctoproject.org/meta-virtualization.git -b ${BRANCH} ${BRANCH}/meta-virtualization
          else
            cd ${BRANCH}/meta-virtualization
            git pull origin ${BRANCH}
            cd ../..
          fi
      - name: Update repo meta-lts-mixins
        run: |
          if [ ! -d ${BRANCH}/meta-lts-mixins ]; then
            git clone https://git.yoctoproject.org/meta-lts-mixins -b ${BRANCH}/u-boot ${BRANCH}/meta-lts-mixins
          else
            cd ${BRANCH}/meta-lts-mixins
            git pull origin ${BRANCH}/u-boot
            cd ../..
          fi
      - name: Configuring
        run: |

          DEBIAN_FRONTEND=noninteractive sudo -E apt-get install -y gettext-base

          rm -f ${BRANCH}/build-${MACHINE}/conf/local.conf
          rm -f ${BRANCH}/build-${MACHINE}/conf/bblayers.conf
          . ./${BRANCH}/poky-${POKY_VERSION}/oe-init-build-env ${BRANCH}/build-${MACHINE}

          bitbake-layers add-layer $GITHUB_WORKSPACE/${BRANCH}/poky-${POKY_VERSION}/meta
          bitbake-layers add-layer $GITHUB_WORKSPACE/${BRANCH}/poky-${POKY_VERSION}/meta-poky
          bitbake-layers add-layer $GITHUB_WORKSPACE/${BRANCH}/poky-${POKY_VERSION}/meta-yocto-bsp
          bitbake-layers add-layer $GITHUB_WORKSPACE/${BRANCH}/meta-openembedded/meta-oe
          bitbake-layers add-layer $GITHUB_WORKSPACE/${BRANCH}/meta-openembedded/meta-python
          bitbake-layers add-layer $GITHUB_WORKSPACE/${BRANCH}/meta-openembedded/meta-networking
          bitbake-layers add-layer $GITHUB_WORKSPACE/${BRANCH}/meta-openembedded/meta-filesystems
          bitbake-layers add-layer $GITHUB_WORKSPACE/${BRANCH}/meta-security/meta-tpm
          bitbake-layers add-layer $GITHUB_WORKSPACE/${BRANCH}/meta-virtualization

          bitbake-layers add-layer $GITHUB_WORKSPACE/${BRANCH}/meta-rauc

          if [[ $MACHINE =~ ^qemux86-64$ ]]; then
            bitbake-layers add-layer $GITHUB_WORKSPACE/${BRANCH}/meta-rauc-community/meta-rauc-qemux86
          fi

          if [[ $MACHINE =~ ^raspberrypi.* ]]; then
            bitbake-layers add-layer $GITHUB_WORKSPACE/${BRANCH}/meta-raspberrypi
            bitbake-layers add-layer $GITHUB_WORKSPACE/${BRANCH}/meta-rauc-community/meta-rauc-raspberrypi
          fi

          if [[ $MACHINE =~ ^beaglebone-yocto$ ]]; then
            bitbake-layers add-layer $GITHUB_WORKSPACE/${BRANCH}/meta-rauc-community/meta-rauc-beaglebone
          fi

          if [[ $MACHINE =~ ^raspberrypi5$ ]]; then
            bitbake-layers add-layer $GITHUB_WORKSPACE/${BRANCH}/meta-lts-mixins
          fi

          bitbake-layers add-layer $GITHUB_WORKSPACE/meta-qbee
          bitbake-layers add-layer $GITHUB_WORKSPACE/meta-container-os

          cat > conf/local.conf <<EOF
          CONF_VERSION = "2"
          DISTRO = "qbee-cos"
          MACHINE="${MACHINE}"
          SSTATE_DIR="$GITHUB_WORKSPACE/sstate-${POKY_VERSION}"
          TMPDIR="$GITHUB_WORKSPACE/tmp-${POKY_VERSION}"
          DL_DIR="$GITHUB_WORKSPACE/downloads"
          INHERIT += "rm_work"
          EOF

          if [[ $MACHINE =~ ^qemux86-64$ ]]; then
            cat >> conf/local.conf <<EOF
          MACHINE_FEATURES:append = " pcbios efi"
          EXTRA_IMAGEDEPENDS += "ovmf"
          EOF
          fi

          if [[ $MACHINE =~ ^raspberrypi.* ]]; then
            cat >> conf/local.conf <<EOF
          ENABLE_UART = "1"
          RPI_USE_U_BOOT = "1"
          IMAGE_FSTYPES = "ext4 wic.bz2 wic.bmap"
          SDIMG_ROOTFS_TYPE = "ext4"
          ENABLE_SPI_BUS = "1"
          ENABLE_I2C = "1"
          IMAGE_INSTALL:append = " kernel-modules udev-rules-rpi"
          EOF
          fi

      - name: Building
        id: build
        run: |
          . ./${BRANCH}/poky-${POKY_VERSION}/oe-init-build-env ${BRANCH}/build-${MACHINE}

          # on spdx issues related to u-boot do, 
          bitbake -c cleanall u-boot-tools-native core-image-minimal
          bitbake u-boot-tools-native
          # bitbake -c create_spdx u-boot-tools-native
          # bitbake -c do_create_runtime_spdx u-boot-tools-native

          bitbake -k core-image-minimal

          UPDATE_BUNDLE="update-bundle"

          if [[ $MACHINE =~ ^qemux86-64$ ]]; then
            UPDATE_BUNDLE="qemu-demo-bundle"
          fi
          
          bitbake -k -c cleanall $UPDATE_BUNDLE
          bitbake -k $UPDATE_BUNDLE
          
          cp $GITHUB_WORKSPACE/tmp-${POKY_VERSION}/deploy/images/${MACHINE}/core-image-minimal-${MACHINE}.rootfs.wic.bz2 $GITHUB_WORKSPACE/${MACHINE}-${POKY_VERSION}.wic.bz2
          cp $GITHUB_WORKSPACE/tmp-${POKY_VERSION}/deploy/images/${MACHINE}/${UPDATE_BUNDLE}-${MACHINE}.raucb $GITHUB_WORKSPACE/${MACHINE}-${POKY_VERSION}.raucb
          