---
name: CI
on:
  push:
    branches: [NOJIRA-qbee-docker-os]
    tags:
      - '*'
  pull_request:
    branches: [NOJIRA-qbee-docker-os]

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]
    timeout-minutes: 600
    container:
      image: dynamicdevices/yocto-ci-build:latest
      options: --privileged --platform linux/amd64  -v /dev/net/tun:/dev/net/tun -v /dev/kvm:/dev/kvm
    strategy:
      matrix:
        branch: [scarthgap]
        machine: [qemux86-64]
    env:
      name: build-and-test
      MACHINE: ${{ matrix.machine }}
      BRANCH: ${{ matrix.branch }}
    steps:
      - uses: actions/checkout@v3
        with:
          clean: false
          fetch-depth: 0

      - name: Update repo poky
        run: |
          if [ ! -d ${BRANCH}/poky ]; then
            git clone git://git.yoctoproject.org/poky -b ${BRANCH} ${BRANCH}/poky
          else
            cd ${BRANCH}/poky
            git pull origin ${BRANCH}
            cd ../..
          fi
      - name: Update repo meta-openembedded
        run: |
          if [ ! -d ${BRANCH}/meta-openembedded ]; then
            git clone https://github.com/openembedded/meta-openembedded.git -b ${BRANCH} ${BRANCH}/meta-openembedded
          else
            cd ${BRANCH}/meta-openembedded
            git pull origin ${BRANCH}
            cd ../..
          fi
      - name: Update repo meta-qbee
        run: |
          pwd
          ls -ltr
      
      - name: Configuring
        run: |

          DEBIAN_FRONTEND=noninteractive sudo -E apt-get install -y gettext-base

          rm -f ${BRANCH}/build-${MACHINE}/conf/local.conf
          rm -f ${BRANCH}/build-${MACHINE}/conf/bblayers.conf
          . ./${BRANCH}/poky/oe-init-build-env ${BRANCH}/build-${MACHINE}

          bitbake-layers add-layer $GITHUB_WORKSPACE/${BRANCH}/poky/meta
          bitbake-layers add-layer $GITHUB_WORKSPACE/${BRANCH}/poky/meta-poky
          bitbake-layers add-layer $GITHUB_WORKSPACE/${BRANCH}/poky/meta-yocto-bsp
          bitbake-layers add-layer $GITHUB_WORKSPACE/${BRANCH}/meta-openembedded/meta-oe
          bitbake-layers add-layer $GITHUB_WORKSPACE/meta-qbee

          cat > conf/local.conf <<EOF
          CONF_VERSION = "2"
          INIT_MANAGER = "systemd"
          MACHINE="${MACHINE}"
          SSTATE_DIR="$GITHUB_WORKSPACE/sstate"
          TMPDIR="$GITHUB_WORKSPACE/tmp"
          DL_DIR="$GITHUB_WORKSPACE/downloads"
          MACHINE_FEATURES:append = " pcbios efi" 
          EXTRA_IMAGEDEPENDS += "ovmf"
          WINHERIT += "rm_work"
          EOF

      - name: Building
        id: build
        run: |
          . ./${BRANCH}/poky/oe-init-build-env ${BRANCH}/build-${MACHINE}
          bitbake -k core-image-minimal
