permissions:
  contents: read
name: meta-qbee-pr-tests
on:
  pull_request:
    branches:
      - master
      - kirkstone
      - scarthgap
#      - wrynose

jobs:
  build:
    strategy:
      matrix:
        machine: [qemux86-64,qemuarm64]
    runs-on: [self-hosted, Linux, X64]
    timeout-minutes: 600
    container:
      image: ghcr.io/siemens/kas/kas:5.2 # Use the latest kas container image
      options: --user 1000:1000
      env:
        KAS_CLONE_DEPTH: 0
        DL_DIR: /ci/yocto/downloads
        SSTATE_DIR: /ci/yocto/sstate
        TMPDIR: /ci/yocto/tmp
        # Environment variable for bootstrap key
        # This should be set in the GitHub repository secrets for security
        # when running integration tests with the platform
        QBEE_BOOTSTRAP_KEY: my-bootstrap-key
      volumes:
        - /home/runner/ci/yocto:/ci/yocto
    steps:
      - uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 0

      - name: Set up KAS
        env:
          KAS_MACHINE: ${{ matrix.machine }}
          TARGET_BRANCH: ${{ github.base_ref }}
          HEAD_BRANCH: ${{ github.head_ref }}
        run: |
          python3 -c 'import os,sys; print(os.path.expandvars(sys.stdin.read()))' \
            < kas-qbee-agent.yml.template > kas-qbee-agent.yml

          cat kas-qbee-agent.yml # Debug output to verify the generated KAS configuration
          kas checkout kas-qbee-agent.yml

      - name: Build with KAS
        env:
          KAS_MACHINE: ${{ matrix.machine }}
        run: |
          kas build kas-qbee-agent.yml